name: Pull Request

on: [pull_request]

jobs:
  pre-commit:
    runs-on: latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: pre-commit/action@v2.0.3
